### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by yangwei549** [wxh0402/DNFCalculating#14]
勾选红色宠物装备在退出后不会保存，再次开启计算器还要再勾上；鬼泣的刀阵设置也不会保存，而且方块和钩算出的刀阵伤害是一样的（如图），没弄懂这两个形状有什么区别；红阵选10级以上每次开计算器都有提示，有点麻烦，如果能对这些问题做些改动就太感谢了
![QQ截图20200711033011](https://user-images.githubusercontent.com/67332616/87191383-e5cfdd00-c326-11ea-93f7-89e4263a7957.png)
![QQ截图20200711033022](https://user-images.githubusercontent.com/67332616/87191388-e7010a00-c326-11ea-8382-9e38248757de.png)

**Comment by wxh0402** [comment]
已解决
