### ISSUE TITLE
鬼泣鬼斩数据＆符文与技能面板

### ISSUE THREAD

**Issue by yangwei549** [wxh0402/DNFCalculating#16]
鬼泣鬼斩的数据有误，有一部分原因是鬼斩TP不加**鬼斩冲击波**的攻击力，而计算器里改动TP会加，不过计算器使用的技能数据本身应该也有误差

护石符文对技能的百分比有加成，为乘算，加成会显示在技能栏里，可以考虑在计算器内显示这个加成

影响技能百分比的只有TP，技能等级，护石和符文，这里就不截图面板了

![QQ截图20200712224253](https://user-images.githubusercontent.com/67332616/87249353-3400ef80-c491-11ea-985c-70fd4bc4a63c.png)
![QQ截图20200712224304](https://user-images.githubusercontent.com/67332616/87249355-35321c80-c491-11ea-9923-c2815bdad3c4.png)
![QQ截图20200712224312](https://user-images.githubusercontent.com/67332616/87249358-35cab300-c491-11ea-8f65-60eb6bad2b14.png)
![QQ截图20200712224320](https://user-images.githubusercontent.com/67332616/87249359-35cab300-c491-11ea-9cbb-e11a129a6a4e.png)

**Comment by yangwei549** [comment]
后面又研究了一下，每当**噬灵鬼斩等级+1，鬼斩剑气伤害加10%**，计算器内的鬼斩数据也有误差；我在这里提供一个自己测的鬼斩技能数据，大佬们有空可以验算一下（成长忽高忽低，这里取整数）

鬼斩基础值：923%
剑气基础值：897%
鬼斩成长：113%
剑气成长：110%

**Comment by yangwei549** [comment]
![QQ截图20200713022459](https://user-images.githubusercontent.com/67332616/87253735-1db65c00-c4b0-11ea-8e38-fc0f354b96cf.png)
![QQ截图20200713022515](https://user-images.githubusercontent.com/67332616/87253736-1ee78900-c4b0-11ea-92f5-fedd32d92012.png)

**Comment by wxh0402** [comment]
已解决
