### ISSUE TITLE
元素天雷误差比较大

### ISSUE THREAD

**Issue by asqw6677** [wxh0402/DNFCalculating#20]
按照自己的配置设置以后只有天雷有比较明显的误差，使用的是11.30版本
使用天雷护石而且不用符文情况下
![tl2](https://user-images.githubusercontent.com/46427027/97786574-6c1a7280-1be7-11eb-8917-f66d852747bd.jpg)
数据面板也和游戏内有出入
![tl1](https://user-images.githubusercontent.com/46427027/97786584-87857d80-1be7-11eb-9b2b-e49d6fa19762.jpg)
![tlg1](https://user-images.githubusercontent.com/46427027/97786586-89e7d780-1be7-11eb-8376-58050b7961bd.jpg)

**Comment by wxh0402** [comment]
额。。最新的才11.03

**Comment by wxh0402** [comment]
新版本已修正，为护石问题

**Comment by asqw6677** [comment]
谢谢！ 日期是打错了
