### ISSUE TITLE
女机械即使设置了机场是/CD 25秒桩即使CD小于25秒在统计的时候仍然只能打1次

### ISSUE THREAD

**Issue by cdzcdzcdzcdz** [wxh0402/DNFCalculating#28]
用歧路 时空旅行者 和符文把CD压到21.1秒
选择25秒桩仍然只显示打一次
压到19秒才会打两次 这是为啥
是考虑了机场打不完吗？但选了光能量反应模块后机场应该是瞬发的吧
25秒桩 20秒CD的机场应该放两次绰绰有余吧

**Comment by wxh0402** [comment]
问了职业相关的作者，她是将点光能和不点光能的机场设置为两个技能了
点光能的话，把机场设置成0，看光能的伤害就行

**Comment by cdzcdzcdzcdz** [comment]
谢谢！我明白了:)
