### ISSUE TITLE
装备版本以及增幅版本设为TYF以及HF时，小魔女计算时会显示无有效组合

### ISSUE THREAD

**Issue by Cilas-hu** [wxh0402/DNFCalculating#31]
装备版本以及增幅版本设为TYF以及HF时，小魔女计算时会显示无有效组合，实测两项都切回GF可以正常计算
![1](https://user-images.githubusercontent.com/77257530/104146015-28709000-5404-11eb-91ea-b8b91c41089d.png)
![2](https://user-images.githubusercontent.com/77257530/104146019-2ad2ea00-5404-11eb-9ea4-034d811aa9d3.png)

**Comment by Cilas-hu** [comment]
![1](https://user-images.githubusercontent.com/77257530/104146156-b2205d80-5404-11eb-999e-3d4def97c299.png)
![2](https://user-images.githubusercontent.com/77257530/104146159-b3ea2100-5404-11eb-944d-6d6c7723a264.png)

**Comment by wxh0402** [comment]
已解决
