### ISSUE TITLE
有计划优化一下智慧产物的计算逻辑吗

### ISSUE THREAD

**Issue by xdsoar** [wxh0402/DNFCalculating#35]
用单件模式算全量装备计算量太大了没法算吧（而且单件模式的组合数好像不准？和实际计算时的计算数量好像对不上）
因为限制了产物装备的数量 而且正常来说产物只会用来替换3332中的2或者3 这里的计算逻辑可以优化一下吧

**Comment by wxh0402** [comment]
无计划
